midexamlo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votes/', include("votes.urls")),
]

votes/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'votes'


urlpatterns = [
    path('',views.index,name ="index"),
    path('register',views.create,name ="create"),
    path('positions',views.create_position,name ="create_position"),
    path('<int:c_id>',views.detail,name ="detail"),
    #path('<int:post>',views.detail,name ="detail"),
    path('<int:c_id>/update',views.update,name ="update"),
    path('<int:c_id>/vote',views.vote,name ="vote"),
]

votes/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Position(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Candidate(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    position = models.ForeignKey(Position,on_delete=models.CASCADE)
    birthdate = models.DateTimeField(default=datetime.now ,blank=True)
    platform = models.TextField()


class Vote(models.Model):
    candidate = models.ForeignKey(Candidate,on_delete=models.CASCADE)
    vote_datetime = models.DateTimeField( auto_now=True)

votes/forms.py
from django.forms import ModelForm
from .models import Candidate,Position,Vote

class CandidateModelForm(ModelForm):
    class Meta:
        model = Candidate
        exclude = ['id']

class PositionModelForm(ModelForm):
    class Meta:
        model = Position
        exclude = ['id']

votes/views.py
from django.shortcuts import render,redirect
from .models import Candidate,Position,Vote
from .forms import CandidateModelForm,PositionModelForm
from datetime import datetime 
# Create your views here.
def index(request):
    context = {} #params
    candidates = Candidate.objects.all()
    context['candidates']=candidates
    return render(request,"index.html",context)

def create(request):
    context={}
    if(request.method == 'POST'):
        form = CandidateModelForm(request.POST)
        if(form.is_valid()):
            form.save()#this fucking returns the object it saves !!!!!!!!!!
            return redirect('votes:index')
        else:
            context['candidate_form']=form
            return render(request,'candidate_create.html',context)
    else:
        form = CandidateModelForm()
        context['candidate_form']=form
        return render(request,'candidate_create.html',context)

def create_position(request):
    context={}
    if(request.method == 'POST'):
        form = PositionModelForm(request.POST)
        if(form.is_valid()):
            form.save()#this fucking returns the object it saves !!!!!!!!!!
            return redirect('votes:index')
        else:
            context['position_form']=form
            return render(request,'position_create.html',context)
    else:
        form = PositionModelForm()
        context['position_form']=form
        return render(request,'position_create.html',context)

def detail(request, c_id):
    context={}
    c = Candidate.objects.get(id=c_id)
    votes_total = Vote.objects.filter(candidate = c).count
    context['candidate'] = c
    context["votes_total"] = votes_total
    return render(request,"detail.html",context)

def update(request, c_id):
    context ={}
    context["id"]=c_id
    c = Candidate.objects.get(id=c_id)
    if(request.method == 'POST'):
        form = CandidateModelForm(request.POST, instance=c)
        if form.is_valid():  #data val
            form.save()
            return redirect('votes:detail',c_id)
        else:
            context['candidate_form']=form
            return render(request,'update.html',context)
    else:
        context['candidate_form'] =CandidateModelForm(instance=c)
        return render(request,"update.html",context)

def vote(request, c_id):
    context ={}
    c = Candidate.objects.get(id = c_id)
    Vote(candidate = c, vote_datetime= datetime.now()).save()
    return redirect('votes:detail',c_id)
    

votes/templates/base.html
{% load static %}<!-- template tags -->
<html>
    <head>
        <title>
            {% block head %}
                this is the head 
            {% endblock %}
        </title>
        <link rel="stylesheet" type="text/css" href="{% static 'votes/materialize/css/materialize.min.css' %}"\>
        {% block styles %}
        {% endblock %}
    </head>
    <body>
        {% block body %} <!--block(start) body is name-->
            this is the body 
        {% endblock %}
    </body>
    <script src="{% static 'votes/materialize/js/materialize.min.js' %}"></script>
    {% block script %}
    {% endblock %}
</html>

votes/templates/candidate_create.html
{% extends 'base.html' %} 

{% block body %}

<form action="{% url 'votes:create' %}" method="POST">
    {% csrf_token %}
    firstname: {{ candidate_form.firstname  }}
    <br/>
    lastname: {{ candidate_form.lastname  }}
    <br/>
    position: {{ candidate_form.position  }}
    <br/>
    birthdate: <input type="date" {{ candidate_form.birthdate  }}> 
    <br/>
    platform: {{ candidate_form.platform  }}
    <br/>
    <input type="submit" value="Post">
    {{ candidate_form.errors }}

</form>
<br/>
<a href="{% url 'votes:index' %}">Home</a> 


{% endblock %}

votes/templates/detail.html
{% extends 'base.html' %} 

{% block body %}

    firstname: {{ candidate.firstname  }}
    <br/>
    lastname: {{ candidate.lastname  }}
    <br/>
    position: {{ candidate.position  }}
    <br/>
    birthdate:  {{ candidate.birthdate  }}
    <br/>
    platform: {{ candidate.platform  }}
    <br/>
    votes: {{ votes_total }}
    <br/>
    <a href="{% url 'votes:index' %}">Home</a> 
    <br/>
    <a href="{% url 'votes:vote' candidate.id %}">Vote</a> 
    <br/>
    <a href="{% url 'votes:update' candidate.id %}">Update</a> 



{% endblock %}

votes/templates/index.html
{% extends 'base.html' %}

{% block body %}

    <ol>
        {% for c in candidates %}
        <li>
                <a href="{% url 'votes:detail' c.id %}"> {{ c.firstname }} {{ c.lastname }} {{ c.position.name }}</a> 
        </li>
        {% endfor %}
    </ol>
    <a href="{% url 'votes:create'%}">Create Candidate</a> 
    <br/>
    <a href="{% url 'votes:create_position'%}">Create Position</a> 
{% endblock %}

votes/templates/position_create.html
{% extends 'base.html' %} 

{% block body %}

<form action="{% url 'votes:create_position' %}" method="POST">
    {% csrf_token %}
    <table>{{ position_form.as_table }}</table>
    <input type="submit" value="Accept">
    {{ position_form.errors }}
</form>

{% endblock %}

votes/templates/update.html
{% extends 'base.html' %} 

{% block body %}

<form action="{% url 'votes:update' id %}" method="POST">
        {% csrf_token %}
        <table>{{ candidate_form.as_table }}</table>
        <input type="submit" value="Accept">
        {{ candidate_form.errors }}
    </form>

    <br/>
    <a href="{% url 'votes:index' %}">Home</a> 
{% endblock %}